BudgetApp/Models/CostCategory.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using BudgetApp.Models.Interfaces;

namespace BudgetApp.Models
{
    public class CostCategory : BaseEntity, IArchivableEntity
    {
        public CostCategory()
        {
            EntityId = Guid.NewGuid();
            EntityType = nameof(CostCategory);
        }

        [Display(Name = "Category Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Amount Budgeted")]
        [Required]
        public double BudgetedAmount { get; set; }

        public virtual Budget Budget { get; set; }

        #region Interfaces 
        public bool Archived { get; set; }
        public DateTime? ArchiveDate { get; set; }
        public string? ArchivedBy { get; set; }
        #endregion
    }
}

BudgetApp/Controllers/CostCategoryController.cs
using BudgetApp.DataServices;
using BudgetApp.DataServices.ServiceManagers;
using BudgetApp.Models;
using BudgetApp.ViewModels.CostCategoryViewModels;
using Microsoft.AspNetCore.Mvc;
using static BudgetApp.Errors;

namespace BudgetApp.Controllers
{
    public class CostCategoryController : Controller
    {
        ILogger _logger;
        EntityServiceManager _entityServiceManager;
        UserServiceManager _userServiceManager;

        public CostCategoryController(ILogger<CostCategoryController> logger, EntityServiceManager entityServiceManager, UserServiceManager userServiceManager)
        {
            _logger = logger;
            _entityServiceManager = entityServiceManager;
            _userServiceManager = userServiceManager;
        }

        public IActionResult Create(Guid budgetId, string returnUrl)
        {
            Budget? budget = _entityServiceManager.BudgetService.GetById(budgetId);

            if (budget == null)
            {
                return View("Error", GetErrorViewModel(ErrorType.NotFound));
            }

            CostCategoryCreateEditVM viewModel = new CostCategoryCreateEditVM()
            {
                CostCategoryVM = new CostCategoryVM() { CostCategoryId = Guid.NewGuid() },
                ReturnUrl = returnUrl,
                ParentId = budgetId
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(CostCategoryCreateEditVM viewModel)
        {
            if(viewModel.CostCategoryVM.BudgetedAmount <= 0)
            {
                ModelState.AddModelError("CostCategoryVM.BudgetedAmount", "Amount must be greater than 0");
            }

            double amountLeftToAllocate = _entityServiceManager.BudgetService.GetRemainingCategoryAllocationForBudget(viewModel.ParentId);

            if(viewModel.CostCategoryVM.BudgetedAmount > amountLeftToAllocate)
            {
                string error = (amountLeftToAllocate <= 0) ? "You do not have any remaining funds to allocate" : $"You only have {amountLeftToAllocate} remaining to allocate";
                if (amountLeftToAllocate <= 0)
                {
                    ModelState.AddModelError("CostCategoryVM.BudgetedAmount", error);
                }

                ModelState.AddModelError("CostCategoryVM.BudgetedAmount", error);
            }

            if (ModelState.IsValid)
            {
                Budget? budget = _entityServiceManager.BudgetService.GetById(viewModel.ParentId);

                if (budget == null)
                {
                    _logger.LogError("Failed to retrieve budget");
                    return View("Error", GetErrorViewModel(ErrorType.NotFound));
                }

                CostCategory costCategory = new CostCategory()
                {
                    Budget = budget,
                    BudgetedAmount = viewModel.CostCategoryVM.BudgetedAmount,
                    Name = viewModel.CostCategoryVM.Name
                };

                bool success = _entityServiceManager.CostCategoryService.Add(costCategory);
                if (success)
                {
                    _entityServiceManager.SaveChanges();
                    return Redirect(viewModel.ReturnUrl);
                }
                else
                {
                    _logger.LogError("Failed to add cost category to budget");
                    return View("Error", GetErrorViewModel(ErrorType.OperationFailed));
                }
            }

            _logger.LogError("Model is invalid");
            return View(viewModel);
        }

        public IActionResult Edit(Guid costCategoryId, string returnUrl)
        {
            CostCategory? costCategory = _entityServiceManager.CostCategoryService.GetById(costCategoryId, relatedPropertiesToLoad: c => c.Budget);

            if (costCategory == null)
            {
                return View("Error", GetErrorViewModel(ErrorType.NotFound));
            }

            CostCategoryCreateEditVM viewModel = new CostCategoryCreateEditVM()
            {
                CostCategoryVM = new CostCategoryVM()
                {
                    CostCategoryId = costCategory.EntityId,
                    Name = costCategory.Name,
                    BudgetedAmount = costCategory.BudgetedAmount
                },
                ReturnUrl = returnUrl,
                ParentId = costCategory.Budget.EntityId,
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(CostCategoryCreateEditVM viewModel)
        {
            if (viewModel.CostCategoryVM.BudgetedAmount <= 0)
            {
                ModelState.AddModelError("CostCategoryVM.BudgetedAmount", "Amount must be greater than 0");
            }

            if (ModelState.IsValid)
            {
                CostCategory? costCategory = _entityServiceManager.CostCategoryService.GetById(viewModel.CostCategoryVM.CostCategoryId);

                if(costCategory != null)
                {
                    costCategory.Name = viewModel.CostCategoryVM.Name;
                    costCategory.BudgetedAmount = viewModel.CostCategoryVM.BudgetedAmount;

                    bool success = _entityServiceManager.CostCategoryService.Update(costCategory);
                    if (success)
                    {
                        _entityServiceManager.CostCategoryService.SaveChanges();
                        return Redirect(viewModel.ReturnUrl);
                    }
                    else
                    {
                        return View("Error", GetErrorViewModel(ErrorType.OperationFailed));
                    }
                }

                return View("Error", GetErrorViewModel(ErrorType.NotFound));

                
            }

            return View(viewModel);
        }

        public IActionResult Remove(Guid costCategoryId, string returnUrl)
        {
            CostCategory? costCategory = _entityServiceManager.CostCategoryService.GetById(costCategoryId);

            if (costCategory == null)
            {
                return Json(new { title = "Operation Failed", message = "Please contact your administrator for assistance" });
            }

            _entityServiceManager.CostCategoryService.Archive(costCategory);
            _entityServiceManager.SaveChanges();

            return Json( new { status = "success", title = "Success", message = "Category Deleted", returnUrl });
        }
    }
}

BudgetApp/Views/CostCategory/Create.cshtml
@model BudgetApp.ViewModels.CostCategoryViewModels.CostCategoryCreateEditVM

<div class="row text-theme text-center mb-4">
    <h1 class="display-4">
        Create Category
    </h1>
</div>
<form method="post" asp-action="Create" asp-controller="CostCategory">
    <input asp-for="@Model.ReturnUrl" type="hidden" />
    <input asp-for="@Model.ParentId" type="hidden" />
    <div class="form-row my-2">
        @Html.EditorFor(m => m.CostCategoryVM)
    </div>
    <div class="form-row mt-4">
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme mb-4" type="submit">Create</button>
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme" type="button" onclick="location.href='@Model.ReturnUrl'">Cancel</button>
    </div>
</form>

BudgetApp/Views/CostCategory/Edit.cshtml
@model BudgetApp.ViewModels.CostCategoryViewModels.CostCategoryCreateEditVM

<div class="row text-theme text-center mb-4">
    <h1 class="display-1">
        Edit Category
    </h1>
</div>
<form method="post" asp-action="Edit" asp-controller="CostCategory">
    <input asp-for="@Model.ReturnUrl" type="hidden" />
    <input asp-for="@Model.ParentId" type="hidden" />
    <div class="form-row my-2">
        @Html.EditorFor(m => m.CostCategoryVM)
    </div>
    <div class="form-row mt-4">
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme mb-4" type="submit">Save</button>
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme" type="button" onclick="location.href='@Model.ReturnUrl'">Cancel</button>
    </div>
</form>

BudgetApp/Views/CostCategory/_EntityCostCategoryTable.cshtml
@using BudgetApp.ViewModels;
@using BudgetApp.ViewModels.CostCategoryViewModels;
@model EntityCollectionVM<CostCategoryVM>

<div class="my-4">
    <div class="row">
        <div class="col-md-4">
            <label class="h5 text-theme">Expense Categories</label>
        </div>
    </div>
    <div class="row m-0 header-theme border rounded-2 align-items-center text-center py-2">
        <div class="col-4">
            Name
        </div>
        <div class="col-4">
            Amount
        </div>
        <div class="col-3 offset-1">
            <a href="@Url.Action("Create", "CostCategory", new { budgetId = Model.EntityId, returnUrl = Model.ReturnUrl })">
                <i class="bi icon-theme-contrast bi-plus-circle" style="font-size: 1.5rem"></i>
            </a>
        </div>
    </div>

    @if (Model.EntityItems.Count() == 0)
    {
        <div class="row row-theme rounded-2 border text-center py-2 m-0">
            <div class="col-12">
                No Cost Categories to Display
            </div>
        </div>
    }
    else
    {
        foreach (CostCategoryVM costCategory in Model.EntityItems)
        {
            <div class="row m-0 row-theme rounded-2 border align-items-center text-center py-2">
                <div class="col-4">
                    @costCategory.Name
                </div>
                <div class="col-4">
                    @costCategory.BudgetedAmount.GetCurrencyFormat()
                </div>
                <div class="col-3 offset-1">
                    <div class="row">
                        <div class="col-6">
                            <a href="@Url.Action("Edit", "CostCategory", new { costCategoryId = costCategory.CostCategoryId, returnUrl = Model.ReturnUrl})">
                                <i class="bi icon-theme bi-pencil-square" style="font-size: 1.5rem"></i>
                            </a>
                        </div>
                        <div class="col-6">
                            <a onclick="ShowConfirmModal('Are you sure you want to delete this item?', '@Url.Action("Remove", "CostCategory", new { costCategoryId = costCategory.CostCategoryId, returnUrl = Model.ReturnUrl})')">
                                <i class="bi icon-theme bi-trash" style="font-size: 1.5rem"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>