BudgetApp/Models/FixedCost.cs
using BudgetApp.Models.Interfaces;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;

namespace BudgetApp.Models
{
    public class FixedCost : BaseEntity, IArchivableEntity
    {
        public FixedCost()
        {
            EntityId = Guid.NewGuid();
            EntityType = nameof(FixedCost);
            Description = string.Empty;
        }

        public DateTime MonthBegin { get; set; }

        public DateTime MonthEnd { get; set; }

        [Required(ErrorMessage = "Amount is required")]
        public double Amount { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

        public virtual Budget Budget { get; set; }

        #region Interfaces
        public bool Archived { get; set; }

        public DateTime? ArchiveDate { get; set; }

        public string? ArchivedBy { get; set; }
        #endregion
    }
}

BudgetApp/Controllers/FixedCostController.cs
using BudgetApp.DataServices.ServiceManagers;
using BudgetApp.Models;
using BudgetApp.ViewModels.FixedCostViewModels;
using BudgetApp.ViewModels.IncomeViewModels;
using Microsoft.AspNetCore.Mvc;
using static BudgetApp.Errors;

namespace BudgetApp.Controllers
{
    public class FixedCostController : Controller
    {
        ILogger _logger;
        EntityServiceManager _entityServiceManager;
        UserServiceManager _userServiceManager;

        public FixedCostController(ILogger<FixedCostController> logger, EntityServiceManager entityServiceManager, UserServiceManager userServiceManager)
        {
            _logger = logger;
            _entityServiceManager = entityServiceManager;
            _userServiceManager = userServiceManager;
        }

        public IActionResult Create(Guid budgetId, string returnUrl)
        {
            Budget? budget = _entityServiceManager.BudgetService.GetById(budgetId);

            if (budget == null)
            {
                return View("Error", GetErrorViewModel(ErrorType.NotFound));
            }

            FixedCostCreateEditVM viewModel = new FixedCostCreateEditVM()
            {
                FixedCostVM = new FixedCostVM(),
                ReturnUrl = returnUrl,
                ParentId = budgetId
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(FixedCostCreateEditVM viewModel)
        {
            if (viewModel.FixedCostVM.Amount <= 0)
            {
                ModelState.AddModelError("FixedCostVM.Amount", "Amount must be greater than 0");
            }

            if (ModelState.IsValid)
            {
                Budget? budget = _entityServiceManager.BudgetService.GetById(viewModel.ParentId);
                if (budget == null)
                {
                    _logger.LogError("Failed to retrieve budget");
                    return View("Error", GetErrorViewModel(ErrorType.NotFound));
                }

                FixedCost fixedCost = new FixedCost()
                {
                    Budget = budget,
                    Amount = viewModel.FixedCostVM.Amount,
                    Description = viewModel.FixedCostVM.Description,
                    MonthBegin = DateTime.Now.GetMonthBegin(),
                    MonthEnd = DateTime.Now.GetMonthEnd()
                };

                bool success = _entityServiceManager.FixedCostService.Add(fixedCost);
                if (success)
                {
                    _entityServiceManager.SaveChanges();
                    return Redirect(viewModel.ReturnUrl);
                }
                else
                {
                    _logger.LogError("Failed to add fixed cost to budget");
                    return View("Error", GetErrorViewModel(ErrorType.OperationFailed));
                }
            }

            _logger.LogError("Model is invalid");
            return View(viewModel);
        }

        public IActionResult Edit(Guid fixedCostId, string returnUrl)
        {
            FixedCost? fixedCost = _entityServiceManager.FixedCostService.GetById(fixedCostId, relatedPropertiesToLoad: f => f.Budget);

            if (fixedCost == null)
            {
                return View("Error", GetErrorViewModel(ErrorType.NotFound));
            }

            FixedCostCreateEditVM viewModel = new FixedCostCreateEditVM()
            {
                FixedCostVM = new FixedCostVM()
                {
                    FixedCostId = fixedCost.EntityId,
                    Amount = fixedCost.Amount,
                    Description = fixedCost.Description
                },
                ReturnUrl = returnUrl,
                ParentId = fixedCost.Budget.EntityId,
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(FixedCostCreateEditVM viewModel)
        {
            if (viewModel.FixedCostVM.Amount <= 0)
            {
                ModelState.AddModelError("FixedCostVM.Amount", "Amount must be greater than 0");
            }

            if (ModelState.IsValid)
            {
                FixedCost? fixedCost = _entityServiceManager.FixedCostService.GetById(viewModel.FixedCostVM.FixedCostId);

                if(fixedCost != null)
                {
                    fixedCost.Amount = viewModel.FixedCostVM.Amount;
                    fixedCost.Description = viewModel.FixedCostVM.Description;

                    bool success = _entityServiceManager.FixedCostService.Update(fixedCost);
                    if (success)
                    {
                        _entityServiceManager.SaveChanges();
                        return Redirect(viewModel.ReturnUrl);
                    }
                    else
                    {
                        return View("Error", GetErrorViewModel(ErrorType.OperationFailed));
                    }
                }

                return View("Error", GetErrorViewModel(ErrorType.NotFound));
            }

            return View(viewModel);
        }

        public IActionResult Remove(Guid fixedCostId, string returnUrl)
        {
            FixedCost? fixedCost = _entityServiceManager.FixedCostService.GetById(fixedCostId);

            if (fixedCost == null)
            {
                return Json(new { title = "Operation Failed", message = "Please contact your administrator for assistance" });
            }

            _entityServiceManager.FixedCostService.Archive(fixedCost);
            _entityServiceManager.SaveChanges();

            return Json(new { status = "success", title = "Success", message = "Fixed Cost Deleted", returnUrl });
        }
    }
}

BudgetApp/Views/FixedCost/Create.cshtml
@model BudgetApp.ViewModels.FixedCostViewModels.FixedCostCreateEditVM

<div class="row text-theme text-center mb-4">
    <h1 class="display-4">
        Create Monthly Cost
    </h1>
</div>
<form method="post" asp-action="Create" asp-controller="FixedCost">
    <input asp-for="@Model.ReturnUrl" type="hidden" />
    <input asp-for="@Model.ParentId" type="hidden" />
    <div class="form-row my-2">
        @Html.EditorFor(m => m.FixedCostVM)
    </div>
    <div class="form-row mt-4">
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme mb-4" type="submit">Create</button>
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme" type="button" onclick="location.href='@Model.ReturnUrl'">Cancel</button>
    </div>
</form>

BudgetApp/Views/FixedCost/Edit.cshtml
@model BudgetApp.ViewModels.FixedCostViewModels.FixedCostCreateEditVM

<div class="row text-theme text-center mb-4">
    <h1 class="display-4">
        Edit Monthly Cost
    </h1>
</div>
<form method="post" asp-action="Edit" asp-controller="FixedCost">
    <input asp-for="@Model.ReturnUrl" type="hidden" />
    <input asp-for="@Model.ParentId" type="hidden" />
    <div class="form-row my-2">
        @Html.EditorFor(m => m.FixedCostVM)
    </div>
    <div class="form-row mt-4">
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme mb-4" type="submit">Save</button>
        <button class="col-md-4 offset-md-4  col-8 offset-2 p-md-3 p-2 btn btn-theme" type="button" onclick="location.href='@Model.ReturnUrl'">Cancel</button>
    </div>
</form>

BudgetApp/Views/FixedCost/_EntityFixedCostTable.cshtml
@using BudgetApp.ViewModels;
@using BudgetApp.ViewModels.FixedCostViewModels;
@model EntityCollectionVM<FixedCostVM>

<div class="my-4">
    <div class="row">
        <div class="col-md-4">
            <label class="h5 text-theme">Monthly Costs</label>
        </div>
    </div>
    <div class="row m-0 header-theme rounded-2 align-items-center border text-center py-2">
        <div class="col-4">
            Description
        </div>
        <div class="col-4">
            Amount
        </div>
        <div class="col-3 offset-1">
            <a href="@Url.Action("Create","FixedCost", new { budgetId = Model.EntityId, entityType = Model.EntityType, returnUrl = Model.ReturnUrl })">
                <i class="bi icon-theme-contrast bi-plus-circle"></i>
            </a>
        </div>
    </div>

    @if (Model.EntityItems.Count() == 0)
    {
        <div class="row m-0 row-theme rounded-2 border text-center py-2">
            <div class="col-12">
                No Fixed Costs to Display
            </div>
        </div>
    }
    else
    {
        foreach (FixedCostVM fixedCost in Model.EntityItems)
        {
            <div class="row m-0 row-theme rounded-2 align-items-center border text-center py-2">
                <div class="col-4">
                    @fixedCost.Description
                </div>
                <div class="col-4">
                    @fixedCost.Amount.GetCurrencyFormat()
                </div>
                <div class="col-3 offset-1">
                    <div class="row">
                        <div class="col-6">
                            <a href="@Url.Action("Edit", "FixedCost", new { fixedCostId = fixedCost.FixedCostId, returnUrl = Model.ReturnUrl})">
                                <i class="bi icon-theme bi-pencil-square"></i>
                            </a>
                        </div>
                        <div class="col-6">
                            <a onclick="ShowConfirmModal('Are you sure you want to delete this item?', '@Url.Action("Remove", "FixedCost", new { fixedCostId = fixedCost.FixedCostId, returnUrl = Model.ReturnUrl })')">
                                <i class="bi icon-theme bi-trash" style="font-size: 1.5rem"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>